server:
  port: 8761

# Service Name
spring:
  application:
    name: discovery

# Eureka Service ? ?? ?? ???? ?? ? ??? ?? ??? false ???
eureka:
  client:
    # default -> true
    register-with-eureka: false
    # default -> true
    fetch-registry: false